SELECT CENTRO_CUSTO,ACCOUNT_CATEGORY FROM GVT_KENAN_SAP_CENTRO_CUSTO 
WHERE CARACTERISTICA_CLIENTE = '1P'
--AND ACCOUNT_CATEGORY = ?
AND TIPO_CONTABILIZACAO = 'Receita'
AND TIPO_PRODUTO = 'Fixa'
;