SELECT  JK.JNL_CODE_ID, JK.ID_TYPE, JK.ID_VALUE, JK.ID_TYPE2, JK.ID_VALUE2,
        JK.USE_CODE, JK.ACCOUNT_CATEGORY, ADJ_CATEGORY, ACTIVE_DATE, INACTIVE_DATE, 
        OPEN_ITEM_ID,NO_JNL_IND, TAX_TYPE_CODE, JC.FML_ACCT_DB, JC.FML_ACCT_CR
FROM    ARBOR.JNL_KEYS JK 
        INNER JOIN ARBOR.JNL_CUSTOM JC
        ON JK.JNL_CODE_ID = JC.JNL_CODE_ID
WHERE   INACTIVE_DATE IS NULL OR INACTIVE_DATE >= SYSDATE -90
;