
DELETE PROATIVO_OWNER.PROATIVO_LOG_EXECUCAO WHERE ID_CENARIO = (SELECT ID_CENARIO FROM PROATIVO_OWNER.PROATIVO_CENARIOS where cenario = 'MONITOR_CONF_CONTABIL');
DELETE proativo_owner.proativo_controle_execucao where id_cenario = (SELECT ID_CENARIO FROM PROATIVO_OWNER.PROATIVO_CENARIOS where cenario = 'MONITOR_CONF_CONTABIL');
DELETE PROATIVO_OWNER.PROATIVO_CENARIOS WHERE ID_CENARIO = (SELECT ID_CENARIO FROM PROATIVO_OWNER.PROATIVO_CENARIOS where cenario = 'MONITOR_CONF_CONTABIL');
delete PROATIVO_OWNER.PROATIVO_GRUPOS_EMAIL where nome_grupo = 'Email Monitor Contabil';
