UPDATE GOV_IT_OWNER.MONIT_CONTABIL_TABELA_VERDADE SET
FAT_CC_DEBITO = ?,
FAT_CC_CREDITO = ?,
A_FAT_CC_DEBITO	= ?, 
A_FAT_CC_CREDITO = ?,
FAT_ADJ_CC_DEBITO = ?,
FAT_ADJ_CC_CREDITO = ?,
A_FAT_ADJ_CC_DEBITO	= ?, 
A_FAT_ADJ_CC_CREDITO = ?
WHERE ID = ?