Insert into EXPORT_TABLE (JNL_CODE_ID,USE_CODE,ID_TYPE,ID_VALUE,ID_TYPE2,
ID_VALUE2,ACCOUNT_CATEGORY,OPEN_ITEM_ID,INACTIVE_DATE,MKT_CODE,NO_JNL_IND,FML_ACCT_DB,FML_ACCT_CR) 
values (?,?,?,?,?,?,?,?,?,?,?,?,?);
