SELECT kss.pos_neg,
            kss.documento_jnl_ref_no jnl_ref_no,
            kss.documento_jnl_ref_no_serv jnl_ref_no_serv,
            kss.empresa_mkt_code mkt_code,
            kss.data_documento jnl_subcycle_end_dt,
            kss.tipo_lancamento id_type,
            kss.id_type2,
            kss.conta_contabil_cr fml_acct_cr,
      kss.conta_contabil_db fml_acct_db,
            kss.centro_de_custo_rev_ctr rev_rcv_cost_ctr,
            kss.bill_ref_no,
            kss.bill_ref_resets,
            kss.account_no,
            kss.external_id,
            kss.account_category,
            kss.open_item_id,
            SUM(kss.montante_valor) valor,
            kss.use_code,
            kss.cod_atribuicao ciclo,
      kss.full_sin_seq,
      kss.tipo_registro,
      kss.moeda,
        kss.divisao,
      kss.centro_custo
   FROM   arborgvt_journals.GVT_KENAN_SAP_SPED_CONT_DET kss
     WHERE  kss.documento_jnl_ref_no = 5026
     AND    kss.documento_jnl_ref_no_serv = 3
   AND    kss.lote = 'P23JNL01.171127_003432_0000502803'
   GROUP BY kss.pos_neg,
              kss.documento_jnl_ref_no,
              kss.documento_jnl_ref_no_serv,
              kss.empresa_mkt_code,
              kss.data_documento,
              kss.tipo_lancamento,
              kss.id_type2,
              kss.conta_contabil_cr,
              kss.conta_contabil_db,
              kss.centro_de_custo_rev_ctr,
              kss.bill_ref_no,
              kss.bill_ref_resets,
              kss.account_no,
              kss.external_id,
              kss.account_category,
              kss.open_item_id,
              kss.use_code,
              kss.cod_atribuicao,
              kss.full_sin_seq,
              kss.tipo_registro,
              kss.moeda,
              kss.divisao,
              kss.centro_custo
     ORDER  BY 2,3,4,5,6,9,8,9,10,1,17;